#ifndef _DEFINES_H
#define _DEFINES_H

#define ERROR_INSTRUCTION  0
#define INSTRUCTIONS_COUNT 1

// Memory layout of ATmega328p
#define MEMORY_ADRESS_START 0x0000 
#define MEMORY_ADRESS_END   0x3FFF 
#define MEMORY_SIZE         16384

#define GP_REGISTERS_MEMORY_START 0x0000 
#define GP_REGISTERS_MEMORY_END   0x001F 
#define GP_REGISTERS_SIZE         32

#define IO_REGISTERS_MEMORY_START 0x0020 
#define IO_REGISTERS_MEMORY_END   0x005F 
#define IO_REGISTERS_SIZE          64

#define EXT_IO_REGISTERS_MEMORY_START 0x0060 
#define EXT_IO_REGISTERS_MEMORY_END   0x00FF 
#define EXT_IO_REGISTERS_SIZE         160

#define SRAM_MEMORY_START 0x0100
#define SRAM_MEMORY_END   0x08ff
#define SRAM_SIZE         2048

#define PROGRAM_MEMORY_SIZE 2048

#endif